---
# handlers file for perfsonar-testpoint

- name: SvcRestart TimeSync
  service:
    name: "{{ timesync_service }}"
    state: restarted

- name: SvcRestart SSH
  service:
    name: "{{ ssh_service }}"
    state: restarted

